print ("PPPPPP", "Y", sep="  ", end="     ")
print ("Y", "TTTTTT", "OOOOOO", "N", sep="  ", end="   ")
print ("N")
print ("P", "P", sep="    ", end="   ") 
print ("Y", "Y", sep="   ", end="     ")
print ("T", "O", sep="     ", end="    ")
print ("O", "NN", "N", sep="  ")
print("PPPPPP", "Y", sep="    ", end=" ")
print ("Y", "T", sep="      ", end="     ")
print ("O", "O", sep="    ", end="  ")
print ("N", "N", "N", sep=" ")
print ("P", "Y", sep="          ", end="       ")
print ("T", "O", sep="     ", end="    ")
print ("O", "N", "NN", sep="  ")
print ("P", "Y", sep="          ", end="       ")
print ("T", "OOOOOO", sep="     ", end="  ")
print ("N", "N", sep="   ")
